=== squm/xml/behemoth.dtd
<!ELEMENT behemoth (
		    Date?,
		    DocumentN+,
		    Time?,
		    Bear?,
		    Giraffe,
		    Zebra*
		    )>
<!ATTLIST behemoth
	type (gray | white) #REQUIRED
>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT DocumentN (#PCDATA)>
<!ELEMENT Time (#PCDATA)>
<!ELEMENT Bear (
		    Address?,
		    Colour?
		    )>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Colour (#PCDATA)>
<!ELEMENT Giraffe (
		   Height?,
		   Mood?
		   )>
<!ELEMENT Height (#PCDATA)>
<!ELEMENT Mood (#PCDATA)>
<!ELEMENT Zebra (
		 ColourOne?,
		 ColourTwo?,
		 Name*
		 )>
<!ELEMENT ColourOne (#PCDATA)>
<!ELEMENT ColourTwo (#PCDATA)>
<!ELEMENT Name (#PCDATA)>

=== squm/xml/wildlife2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE behemoth SYSTEM "behemoth.dtd">
<behemoth type="white">
  <Date/>
  <DocumentN>123</DocumentN>
  <Time/>
  <Bear>
    <Address>New Zealand</Address>
    <Colour/>
  </Bear>
  <Giraffe>
    <Height/>
    <Mood>awake, aroused</Mood>
  </Giraffe>
  <Zebra>
    <ColourOne>white</ColourOne>
    <ColourTwo>black</ColourTwo>
    <Name/>
  </Zebra>
</behemoth>

=== squm/xml/behemoth.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml version="1.0" encoding="UTF-8" standalone="yes"?> -->
<!DOCTYPE behemoth SYSTEM "behemoth.dtd">
<behemoth type="whiteee">
	<DocumentN>123</DocumentN>
	<Date/>
	<Time/>
	<Bear>
		<Address>New Zealand</Address>
		<Colour/>
	</Bear>
	<Zebra>
		<Name/>
		<ColourOne>white</ColourOne>
		<ColourTwo>black</ColourTwo>
	</Zebra>
	<Giraffe>
		<Height/>
		<Mood>awake, aroused</Mood>
	</Giraffe>>
</behemoth>
